### ISSUE TITLE
QuanX

### ISSUE THREAD

**Issue by aocuan** [missuo/FuckSheepGame#3]
大佬这个脚步不好用呀

**Comment by missuo** [comment]
测试过了啊，难道游戏更新了？

**Comment by aocuan** [comment]
啊不是 可能是我太菜不会用大佬 我下载QuanX配置的时候都没下载下来

**Comment by missuo** [comment]
这是 GitHub 的 raw 链接，需要开梯子。

**Comment by aocuan** [comment]
![image](https://user-images.githubusercontent.com/23306072/190371917-bc6b1730-05cf-403b-a539-3e4b5cb1648a.png)
大佬你康康这是咋回事

**Comment by WenYiran6** [comment]
> ![图片](https://user-images.githubusercontent.com/23306072/190371917-bc6b1730-05cf-403b-a539-3e4b5cb1648a.png) 大佬你康康这是咋回事

我也这样

**Comment by missuo** [comment]
统一回复：需要资源解析器

**Comment by missuo** [comment]
general下加入
~~~
# 资源解析器，自定义各类远程资源的转换
resource_parser_url=https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js
~~~

**Comment by WenYiran6** [comment]
> 一般下加入
> 
> ```
> # 资源解析器，自定义各类远程资源的转换
> resource_parser_url=https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js
> ```

解决了，谢谢哥

**Comment by aocuan** [comment]
大佬这个 修改 t 为你自己的 cookies  cookies怎么获得呀

**Comment by missuo** [comment]
> 大佬这个 修改 t 为你自己的 cookies  cookies怎么获得呀
> 
> 

抓包。Stream这些工具都可以
