### ISSUE TITLE
ios quanx 不会用啊，怎么刷

### ISSUE THREAD

**Issue by jiaxiangcheng** [missuo/FuckSheepGame#5]
不会用啊。。。我把作者说的两行代码都复制粘贴到了他说的位置。然后呢？打开游戏第二关还是一样的难啊，没有变成第一关。有没有人带带我 
![IMG_7789](https://user-images.githubusercontent.com/17082256/190536393-f98ea468-22c4-43aa-a785-c5dfb0908709.png)
![IMG_7790](https://user-images.githubusercontent.com/17082256/190536412-79f4a7f4-e0a2-4f12-a39a-1b2562a4221d.png)

**Comment by nanxiangquan** [comment]
同上问，还需要其他操作吗？

**Comment by missuo** [comment]
QuanX需要开启MITM。否则肯定不会生效。开启MITM的时候需要安装证书并且信任。
