### ISSUE TITLE
请问一下大佬，刷通过次数里面的Cookie要怎么获取？

### ISSUE THREAD

**Issue by nanxiangquan** [missuo/FuckSheepGame#6]

**Comment by missuo** [comment]
可以使用Stream、HTTP Catcher、Proxyman任意的抓包工具。前提是需要开启HTTPS解密，信任证书。

**Comment by 6666zx** [comment]
运行py提示{'err_code': 10003, 'err_msg': '没有权限', 'data': None},是不是我取的t不对，我用http catcher抓到请求tk是cookie吗

**Comment by missuo** [comment]
你的cookies没填进去

**Comment by 6666zx** [comment]
> 你的cookies没填进去

第二关变成第一关了，牛逼
