### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by linshuchar** [missuo/FuckSheepGame#8]
![cc042789c6d245da31359b86f89be2f](https://user-images.githubusercontent.com/49833212/190837918-3f2cbb8f-dcf4-4be8-81ab-20a52622e23b.jpg)

**Comment by linshuchar** [comment]
他的链接好像变了 变成了map_info_new?map_id

**Comment by missuo** [comment]
无法更新是因为没有资源解析器

**Comment by missuo** [comment]
> 他的链接好像变了 变成了map_info_new?map_id

一会我看一下更新

**Comment by linshuchar** [comment]
> 

有资源解释器，应该是是网络问题

**Comment by missuo** [comment]
> > 
> 
> 
> 
> 有资源解释器，应该是是网络问题

那你开梯子啊

**Comment by linshuchar** [comment]
这个问题解决了，开了没反应，我抓包链接显示是https://cat-match.easygame2021.com/sheep/v1/game/map_info_new?map_id=90017 是不是因为多了一个_new

**Comment by missuo** [comment]
> 这个问题解决了，开了没反应，我抓包链接显示是https://cat-match.easygame2021.com/sheep/v1/game/map_info_new?map_id=90017 是不是因为多了一个_new

可能是的 我待会改一下

**Comment by missuo** [comment]
Fixed bug on [9b62a4b](https://github.com/missuo/FuckSheepGame/commit/9b62a4bcb35d95e49c0dbd4bf7c71c63ff47cee8)
