### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by weikaide-web3** [missuo/FuckSheepGame#9]
求作者大神更新一下 现在打开quanX 加载完小程序后无法进入游戏界面 咋回事呀

**Comment by missuo** [comment]
已修复。

**Comment by missuo** [comment]
Fixed bug on [9b62a4b](https://github.com/missuo/FuckSheepGame/commit/9b62a4bcb35d95e49c0dbd4bf7c71c63ff47cee8)
